truncate table entries
truncate table entry_domain
truncate table entry_term
truncate table entry_xref
truncate table metadata
truncate table spelling
truncate table term_pos
truncate table terms
truncate table words